name: main
on:
  - push
  - pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'
      - name: make setup
        run: make setup
      - name: make lint
        run: make lint
      - name: make tests
        run: make test
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: run Snyc to check for vulnerabilities
        uses: snyc/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
