name: main
on:
  - push
  - pull_request
jobs:
  setup:
    runs-on: ubuntu-latest
    build:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: run setup
      - run: make setup
      - name: run tests
      - run: make lint
      - run: make test
    


